version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: picklepub_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 99e3337ba0cf80d266a68ba0d6ebaea6
      POSTGRES_DB: picklepub
    ports:
      - "5432:5432"
    volumes:
      - picklepub_db_data:/var/lib/postgresql/data

volumes:
  picklepub_db_data:
